### ISSUE TITLE
Support CentOS 8

### ISSUE THREAD

**Issue by repeatedly** [treasure-data/omnibus-td-agent#205]
Waiting CentOS 8 release: https://wiki.centos.org/About/Building_8

**Comment by vwbusguy** [comment]
I was able to get pretty far into the build with RHEL 8, but it failed with rake failing to resolve bundler/gem_tasks.  I'm wondering if the ruby 2.5 in RHEL8/CentOS8 might be too new for this repo (EL7 shipped ruby-2.0 and the embedded EL7 ships 2.4).

However, it doesn't seem to be a fluentd problem, since I was able to install it directly via ruby with the instructions here: https://docs.fluentd.org/installation/install-by-gem

**Comment by vwbusguy** [comment]
I emailed Treasure Data through their website form.  They replied with a forwarded email from one of their engineers saying it's in progress and provided a link to this very issue.  It's not very reassuring, since they haven't commented here and I haven't seen any work in the repo for it as of yet.

I'm considering packing up the upstream fluentd into a copr repo if there's no traction on this soon.

**Comment by vwbusguy** [comment]
It looks like there's a reference to support for it in the upcoming td-agent 4 - https://github.com/treasure-data/omnibus-td-agent/issues/209

**Comment by repeatedly** [comment]
For td-agent 4, need more time because our resources focus on other important tasks.
We know CentOS 8 is released recently, we need to check CentOS8 environment.

**Comment by vwbusguy** [comment]
RHEL8 was released back in May.  I assume it's the same build, but I'm actually trying to support RHEL8, if it helps for clarity. I can file that as a separate issue, if that might help.

**Comment by vwbusguy** [comment]
Good news.  I was able to build the new td-agent-3.5.1 release on RHEL8 following the build instructions on the README.md and was able to build an rpm for it.  I'll test it out in some lower level environments.  I might add it to a copr repository for now if it might be helpful for others until there's an official treasuredata repo for it.

**Comment by vwbusguy** [comment]
Testing worked fine on the compiled, so I was able to roll out to our RHEL8 servers via Ansible.  Everything works as expected so far - systemd, plugins, forwarding, etc.  

I thought about updating the vagrant file to include CentOS to see if that just works, but I don't have a vbox environment setup at the moment (though I do have kvm/libvirt, vmware, AWS, and Azure environments available).

**Comment by repeatedly** [comment]
Provide td-agent 3.5.1 for CentOS 8: https://td-agent-package-browser.herokuapp.com/3/redhat/8/x86_64

**Comment by markgoddard** [comment]
I have tried using the above repository to install td-agent in a CentOS 8 container, but I get the following error:

`Failed to download metadata for repo 'treasuredata'`

**Comment by vwbusguy** [comment]
Don't use the herokuapp subdomain.  Use packages.treasuredata.com and it will work:

`dnf config-manager --add-repo https://packages.treasuredata.com/3/redhat/8/x86_64/`

or swap out the source in your .repo file with https://packages.treasuredata.com/3/redhat/8/x86_64/

**Comment by markgoddard** [comment]
My mistake - somehow we had escaped the $releasever and $basearch variables in the repo URL. Removed and all working fine. Thanks!
