### ISSUE TITLE
High Vulnerability CVE-2021-28965 on rexml

### ISSUE THREAD

**Issue by chaitrahegde115** [treasure-data/omnibus-td-agent#288]
Hi,
  I am using td-agent 4.2.0 rpm in k8s environment. Default gem rexml version is 3.2.3.1 and Ruby version is 2.7.4. 
CVE-2021-28965 is reported on it. Can you please help me understand the impact of this vulnerability on td-agent?

**Comment by ashie** [comment]
It's false positive, it's already fixed in Ruby 2.7.3 or later:
  * https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-7-3-released/
  * https://github.com/ruby/ruby/commit/b59e5a64be40b93370afbb0accfcb73c4d682045
BTW, for td-agnet 4, please report issues to https://github.com/fluent-plugins-nursery/fluent-package-builder/issues instead of here.
